name: Hello World

on:
  push:
  workflow_dispatch: # handmatig starten

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "👋 Hallo, GitHub Actions is aan het werk!"
